### ISSUE TITLE
【bug】报错：Process finished with exit code -1073740791 (0xC0000409)

### ISSUE THREAD

**Issue by simple123456T** [FeOAr/Gesture-recognition-and-control#1]
Process finished with exit code -1073740791 (0xC0000409)

显存 内存都足够，
是不是有内存泄漏的地方？

![image](https://user-images.githubusercontent.com/104408880/179647240-a80f3e0e-b685-4570-9238-9b8c3f69959d.png)

**Comment by FeOAr** [comment]
我忘说了，"开启控制"那个按钮只能点一次也就是开启一次，点第二次就会卡死，这个问题应该是PyQT5多线程方面的，我没时间修复了，不好意思。需要退出控制可以再点一次“关闭摄像头”，或者直接关掉程序。
