### ISSUE TITLE
这段代码是什么意思

### ISSUE THREAD

**Issue by simple123456T** [FeOAr/Gesture-recognition-and-control#2]
这段代码是为了取最新的 4帧，判断是那个手势吗
![image](https://user-images.githubusercontent.com/104408880/180360304-f98b6c0a-de19-418c-adcd-b1a96789b6b4.png)

**Comment by FeOAr** [comment]
嗯，大意就是建立个滑动窗口，选出现次数最多的类型为结果类型，因为识别的时候常有一瞬间的抖动，需要过滤一下。

**Comment by simple123456T** [comment]
这个滑动窗口的起点是以 ‘5’ 手势第一次出现的位置作为开始点，然后当未来几帧出现在左边的滑动窗口内，就判定为向左滑动，反之，向右滑动。是这样的思路吗？

**Comment by FeOAr** [comment]
这个滑动窗口不判断动作，只是用来稳定检测的结果类型是'5'，'v'或者是'fist',判断运动是在后边翻页附近，用IoU判断是静止还是位移，用x坐标向量方向判断运动方向。

**Comment by simple123456T** [comment]
ok,  你是取过去5帧内出现次数最多的类型作为检测结果，然后根据这五帧内的 IOU 变化值和 x坐标变化方向 来判断运动方向的吗？

**Comment by FeOAr** [comment]
并不是，只是取了连续的5个类型，算个结果类型。IoU和位移是连续两帧（即当前状态和上一帧时刻的状态)的数据做判断

**Comment by simple123456T** [comment]
ok,   好的，谢谢

**Comment by simple123456T** [comment]
我也在做你这样的应用，你这个是距离摄像头1米之内，我这个的应用场景是在会议室场景下，距离摄像头大概2米到3米之间，但是效果不是很好，不知道你有没有一些建议

**Comment by FeOAr** [comment]
1. 分辨率和帧率要高，光线明亮，背景反差大，背景尽量干净。
2. 2到3米也没关系，办法一，参考相机镜头的变焦，增加焦距也是相对拉近了。
3. 我这个时间与能力有限，识别效果或是控制效果不好是正常的，建议在提升识别效果后重新设计解读与控制那部分。甚至可以考虑加一个lstm，因为这种手势也算是带有时间属性的。
4. 针对你的应用场景一定要自采数据集，至少对于这个项目，数据集的好坏影响很大。
5. 我这个参考 [ 丛玉华, 何啸, 邢长达, 等. 基于计算机视觉手势识别的人机交互技术研究[J]. 兵器装备工程学报, 2022,43(01):152-160.]
6. 本科毕设，能力有限，再多不会_(:з)∠)_

**Comment by simple123456T** [comment]
ok，谢谢

**Comment by zhengyuanxing** [comment]
你好，请问有什么好的数据集推荐，或者如何自采数据集？怎样采集？比如说录制视频，一个人还是多个人？

**Comment by FeOAr** [comment]
去年的这个时间，我花了差不多一周在找这种类型的数据集（有手位置以及类型），但是完全找不到。下来说怎么做：1，确定几个环境，如光线的明暗，空间的大小，环境单一与复杂等等；2，可以找几个人（为了后期方便，每次录制视频只出现一只手）以一种手势在空中比划，这是为了让这个收手势出现在图像的任意位置，然后调整人与相机的距离，为了调整手在图像里的大小；3，视频使用60帧或更高，因为低帧率手会拍糊，可以用potplayer抽帧，同时resize。然后就是本仓库readme里的快速标注方法。

大概就这样，有疑问再提。

**Comment by zhengyuanxing** [comment]
人与相机的距离大概是多少，我连接本地以外的第二个相机，然后移动捕捉很慢，这是什么原因？

**Comment by FeOAr** [comment]
检查摄像头是否能流畅使用，检查是否多次开启控制线程。没解决我也就不清楚了。

**Comment by zhengyuanxing** [comment]
好的，谢谢

**Comment by zhengyuanxing** [comment]
你好，摄像头怎么选用手机摄像头，整样才能和你视频里的一样流畅

**Comment by FeOAr** [comment]
lriun webcam这个软件

**Comment by zhengyuanxing** [comment]
需要在哪里修改摄像头，调用除本地以外的摄像头

**Comment by FeOAr** [comment]
直接在界面里左边那滑条就是用来改相机的，你不用ui的话，看看horiznotalSlider也就是滑条相关的代码。

**Comment by zhengyuanxing** [comment]
好的，非常感谢，已解决
