### ISSUE TITLE
control_model 永远不等于1 a

### ISSUE THREAD

**Issue by simple123456T** [FeOAr/Gesture-recognition-and-control#3]
下面的代码没执行啊

![image](https://user-images.githubusercontent.com/104408880/180376634-566da6b1-a0a8-431a-a3f0-322f4714176e.png)

**Comment by FeOAr** [comment]
应该是控制模式你没换吧，有0号和1号，操作界面右下方有个条，拖动一下就能换。

**Comment by simple123456T** [comment]
control_model =0 和 control_model=1 有什么区别？功能不都是一样的吗，还有control_model=2，3， 4 这些没有写吧

**Comment by FeOAr** [comment]
模式1的按键不同，是用来进行图片查看器里的缩放，后边的功能没写，我这个写法属于临时实现目标。

**Comment by simple123456T** [comment]
ok
